// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIMPER.DataP;

#nullable disable

namespace PIMPER.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230313214435_AddTablesToDatabase")]
    partial class AddTablesToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PIMPER.Models.IngredientTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantitiesTableId")
                        .HasColumnType("int");

                    b.Property<int>("UnitTableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuantitiesTableId");

                    b.HasIndex("UnitTableId");

                    b.ToTable("ingredientTables");
                });

            modelBuilder.Entity("PIMPER.Models.QuantitiesTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("quantitiesTables");
                });

            modelBuilder.Entity("PIMPER.Models.RecipeIngredientTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientTableId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeTableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientTableId");

                    b.HasIndex("RecipeTableId");

                    b.ToTable("recipeIngredientTables");
                });

            modelBuilder.Entity("PIMPER.Models.RecipeTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("recipesTable");
                });

            modelBuilder.Entity("PIMPER.Models.UnitTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("unitTables");
                });

            modelBuilder.Entity("PIMPER.Models.IngredientTable", b =>
                {
                    b.HasOne("PIMPER.Models.QuantitiesTable", "QuantitiesTable")
                        .WithMany()
                        .HasForeignKey("QuantitiesTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIMPER.Models.UnitTable", "UnitTable")
                        .WithMany()
                        .HasForeignKey("UnitTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuantitiesTable");

                    b.Navigation("UnitTable");
                });

            modelBuilder.Entity("PIMPER.Models.RecipeIngredientTable", b =>
                {
                    b.HasOne("PIMPER.Models.IngredientTable", "IngredientTable")
                        .WithMany("RecipeIngredientTable")
                        .HasForeignKey("IngredientTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIMPER.Models.RecipeTable", "RecipeTable")
                        .WithMany("RecipeIngredientTable")
                        .HasForeignKey("RecipeTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientTable");

                    b.Navigation("RecipeTable");
                });

            modelBuilder.Entity("PIMPER.Models.IngredientTable", b =>
                {
                    b.Navigation("RecipeIngredientTable");
                });

            modelBuilder.Entity("PIMPER.Models.RecipeTable", b =>
                {
                    b.Navigation("RecipeIngredientTable");
                });
#pragma warning restore 612, 618
        }
    }
}
